### ISSUE TITLE
Wrong rendering of error messages

### ISSUE THREAD

**Issue by mfbehrens99** [mfbehrens99/linter-yalafi#25]
![image](https://user-images.githubusercontent.com/58851724/106750570-4a86b800-6628-11eb-8f52-d440fa418548.png)

I think this is probably due to the latest linter update, however this is only a theory.

**Comment by torik42** [comment]
I just updated both, `linter` and `linter-ui-default`, and have the same problem.

**Comment by torik42** [comment]
By the way, this is not the string `linter-yalafi` creates. The Markdown is already converted to html which supports your theory.

**Comment by mfbehrens99** [comment]
Thanks for your information. They'll probably fix it soon.
